set(WORK_ROOT $ENV{WORK_ROOT})

if("${CLEAN_BUILD}" STREQUAL "true")
    file(REMOVE_RECURSE ${WORK_ROOT}/out)
    file(REMOVE_RECURSE ${WORK_ROOT}/bin)
else()
    include(build_tools/cmake-scripts/get_env.cmake)
    include(libs.cmake)

    foreach(lib ${libs})
        if("${lib}" STREQUAL "v8")
            set(internal_fibjs_ms_target "${FIBJS_MSBUILD_TARGET}")
            build("${CMAKE_CURRENT_SOURCE_DIR}/${lib}" "${WORK_ROOT}" "${lib}")
        else()
            set(internal_fibjs_ms_target "")
            build("${CMAKE_CURRENT_SOURCE_DIR}/${lib}" "${WORK_ROOT}" "${lib}")
        endif()
    endforeach()

    foreach(lib ${libs})
        if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${lib}/test")
            build("${CMAKE_CURRENT_SOURCE_DIR}/${lib}/test" "${WORK_ROOT}" "${lib}_test")
        endif()
    endforeach()
endif()
