find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
	set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
	set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
endif(CCACHE_FOUND)

if(MSVC)
	include(${CMAKE_CURRENT_LIST_DIR}/option_flags_msvc.cmake)
else()
	include(${CMAKE_CURRENT_LIST_DIR}/option_flags_clang.cmake)
endif()
include(${CMAKE_CURRENT_LIST_DIR}/option_config.cmake)
